### ISSUE TITLE
Wiki out-dated on Boost-Frameworks

### ISSUE THREAD

**Issue by RedSTARO** [Miku-UI/manifesto#19]
These example commit for `How to enable Boost-Frameworks` has been removed but still on wiki.
https://github.com/Diva-Room/Miku_device_xiaomi_mona/commits/a12130334605daef8fc7304f127463e82eb21cfe

**Comment by AmeChanRain** [comment]
> These example commit for `How to enable Boost-Frameworks` has been removed but still on wiki. https://github.com/Diva-Room/Miku_device_xiaomi_mona/commits/a12130334605daef8fc7304f127463e82eb21cfe

New repo will be public someday...
