### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by whtry** [Miku-UI/manifesto#20]
"""
whtrys@whtrys-Ubuntu:/media/whtrys/files/mikuui$ lunch miku_unicorn-user
cat: /media/whtrys/files/mikuui/system/sepolicy/prebuilts/api/30.0/plat_pub_versioned.cil: No such file or directory
cat: /media/whtrys/files/mikuui/system/sepolicy/prebuilts/api/31.0/plat_pub_versioned.cil: No such file or directory
cat: /media/whtrys/files/mikuui/system/sepolicy/prebuilts/api/32.0/plat_pub_versioned.cil: No such file or directory
/usr/bin/env: "python": 没有那个文件或目录
cat: /media/whtrys/files/mikuui/system/sepolicy/prebuilts/api/30.0/plat_pub_versioned.cil: No such file or directory
cat: /media/whtrys/files/mikuui/system/sepolicy/prebuilts/api/31.0/plat_pub_versioned.cil: No such file or directory
cat: /media/whtrys/files/mikuui/system/sepolicy/prebuilts/api/32.0/plat_pub_versioned.cil: No such file or directory

============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=14
PRODUCT_INCLUDE_TAGS=com.android.mainline
TARGET_PRODUCT=miku_unicorn
TARGET_BUILD_VARIANT=user
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a-branchprot
TARGET_CPU_VARIANT=generic
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv8-2a
TARGET_2ND_CPU_VARIANT=generic
HOST_OS=linux
HOST_OS_EXTRA=Linux-6.2.0-37-generic-x86_64-Ubuntu-22.04.3-LTS
HOST_CROSS_OS=windows
BUILD_ID=UP1A.231105.003
OUT_DIR=out
============================================
whtrys@whtrys-Ubuntu:/media/whtrys/files/mikuui$ 
"""
"""
whtrys@whtrys-Ubuntu:/media/whtrys/files/mikuui$ make diva
cat: /media/whtrys/files/mikuui/system/sepolicy/prebuilts/api/30.0/plat_pub_versioned.cil: No such file or directory
cat: /media/whtrys/files/mikuui/system/sepolicy/prebuilts/api/31.0/plat_pub_versioned.cil: No such file or directory
cat: /media/whtrys/files/mikuui/system/sepolicy/prebuilts/api/32.0/plat_pub_versioned.cil: No such file or directory
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=14
PRODUCT_INCLUDE_TAGS=com.android.mainline
TARGET_PRODUCT=miku_unicorn
TARGET_BUILD_VARIANT=user
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a-branchprot
TARGET_CPU_VARIANT=generic
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv8-2a
TARGET_2ND_CPU_VARIANT=generic
HOST_OS=linux
HOST_OS_EXTRA=Linux-6.2.0-37-generic-x86_64-Ubuntu-22.04.3-LTS
HOST_CROSS_OS=windows
BUILD_ID=UP1A.231105.003
OUT_DIR=out
============================================
[ 33% 1/3] converting Android.bp files to BUILD files at out/soong/bp2build
FAILED: out/soong/bp2build_files_marker
cd "$(dirname "out/host/linux-x86/bin/soong_build")" && BUILDER="$PWD/$(basename "out/host/linux-x86/bin/soong_build")" && cd / 
&& env -i  "$BUILDER"     --top "$TOP"     --soong_out "out/soong"     --out "out"     --bp2build_marker out/soong/bp2build_file
s_marker --globListDir bp2build_files --globFile out/soong/globs-bp2build_files.ninja -t -l out/.module_paths/Android.bp.list --
available_env out/soong/soong.environment.available --used_env out/soong/soong.environment.used.bp2build_files Android.bp
panic: package "android/soong/generator" already has a package context

goroutine 1 [running]:
github.com/google/blueprint.NewPackageContext({0x11d0cbc, 0x17})
	/media/whtrys/files/mikuui/build/blueprint/package_ctx.go:100 +0x36e
android/soong/android.NewPackageContext(...)
	/media/whtrys/files/mikuui/build/soong/android/package_ctx.go:34
miku/soong/generator.init()
	/media/whtrys/files/mikuui/vendor/miku/build/soong/generator/generator.go:37 +0x25
23:44:12 soong bootstrap failed with: exit status 1

#### failed to build some targets (1 seconds) ####
"""

**Comment by RedSTARO** [comment]
Make sure you have been install python3 by command:
`sudo apt-get install python3`
Try running this in your terminal to create symbol link for python:
`sudo ln -s /usr/bin/python3 /usr/bin/python`

**Comment by whtry** [comment]
> Make sure you have been install python3 by command: `sudo apt-get install python3` Try running this in your terminal to create symbol link for python: `sudo ln -s /usr/bin/python3 /usr/bin/python`

不是你说的这个问题，我已经解决了，不过还是谢谢，是repo的磁盘不是ext4导致的

**Comment by VivekBhagat07** [comment]
> > Make sure you have been install python3 by command:  Try running this in your terminal to create symbol link for python: `sudo apt-get install python3``sudo ln -s /usr/bin/python3 /usr/bin/python`
> 
> It's not the problem you said, I've solved it, but thank you, it's the repo's disk that isn't caused by ext4

hey how did solved pls let me know i'm getting same error

**Comment by RedSTARO** [comment]
> l

The error metioned not finding python.
Make sure you has been configration it correctly first by using "python --version"

**Comment by whtry** [comment]
> > l
> 
> The error metioned not finding python.
> Make sure you has been configration it correctly first by using "python --version"

oh, i fogot to answer you. That day, i checked all of the python environment setting and reinstall it again and again. I am very sure that the python environment setting is right. I suddenly thought that the repo is in another disk. And the file system is btrfs. When i tried to change the disk from btrfs to ext4, the python environment has been fixed by itself. So maybe it's something broken in the file system caused the python environment bug. Thank you for your advice!
