### ISSUE TITLE
commits enabling Miku UI Boost Framework not available

### ISSUE THREAD

**Issue by linlinger** [Miku-UI/manifesto#26]
When I'm reading Chinese version of wiki, I found the commit to enable Miku UI Boost Framework is no longer available ,and the link is https://github.com/Diva-Room/Miku_device_xiaomi_mona/commits/a12130334605daef8fc7304f127463e82eb21cfe

**Comment by AmeChanRain** [comment]
Thanks, we'll update it later. :3

**Comment by AmeChanRain** [comment]
Updated.
