### ISSUE TITLE
Build error, please help me!

### ISSUE THREAD

**Issue by RedSTARO** [Miku-UI/manifesto#7]
I want build for my sony xc, but I meet error, This is device tree: 
https://github.com/RedSTARO/android_device_sony_kugo_MikuUI
https://github.com/RedSTARO/android_device_sony_loire-common_MikuUI
https://github.com/sony-msm8956-dev/android_kernel_sony_msm8956
https://github.com/sony-msm8956-dev/proprietary_vendor_sony

Error like this: 
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=12
TARGET_PRODUCT=miku_kugo
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=generic
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv8-a
TARGET_2ND_CPU_VARIANT=generic
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-5.15.0-48-generic-x86_64-Ubuntu-20.04-LTS
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=SQ3A.220705.003.A1
OUT_DIR=out
PRODUCT_SOONG_NAMESPACES=vendor/sony/kugo device/sony/loire-common vendor/sony/loire-common vendor/qcom/opensource/dataservices vendor/qcom/opensource/data-ipa-cfg-mgr hardware/qcom-caf/msm8952
============================================
22:46:49 ************************************************************
22:46:49 You are building on a machine with 15.6GB of RAM
22:46:49 
22:46:49 The minimum required amount of free memory is around 16GB,
22:46:49 and even with that, some configurations may not work.
22:46:49 
22:46:49 If you run into segfaults or other errors, try reducing your
22:46:49 -j value.
22:46:49 ************************************************************
build/make/core/soong_config.mk:196: warning: BOARD_PLAT_PUBLIC_SEPOLICY_DIR 
has been deprecated. Use SYSTEM_EXT_PUBLIC_SEPOLICY_DIRS instead.
build/make/core/soong_config.mk:197: warning: BOARD_PLAT_PRIVATE_SEPOLICY_DIR
 has been deprecated. Use SYSTEM_EXT_PRIVATE_SEPOLICY_DIRS instead.
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=12
TARGET_PRODUCT=miku_kugo
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=generic
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv8-a
TARGET_2ND_CPU_VARIANT=generic
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-5.15.0-48-generic-x86_64-Ubuntu-20.04-LTS
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=SQ3A.220705.003.A1
OUT_DIR=out
PRODUCT_SOONG_NAMESPACES=vendor/sony/kugo device/sony/loire-common vendor/son
y/loire-common vendor/qcom/opensource/dataservices vendor/qcom/opensource/dat
a-ipa-cfg-mgr hardware/qcom-caf/msm8952
============================================
$(shell date +%y%m%d%H%M) was changed, regenerating...
$(shell date +%y%m%d%H%M) was changed, regenerating...
[ 77% 172/222] including system/sepolicy/Android.mk ...
system/sepolicy/Android.mk:57: warning: BOARD_PLAT_PUBLIC_SEPOLICY_DIR has be
en deprecated. Use SYSTEM_EXT_PUBLIC_SEPOLICY_DIRS instead.
system/sepolicy/Android.mk:62: warning: BOARD_PLAT_PRIVATE_SEPOLICY_DIR has b
een deprecated. Use SYSTEM_EXT_PRIVATE_SEPOLICY_DIRS instead.
[100% 222/222] writing build rules ...
build/make/core/Makefile:61: warning: overriding commands for target `out/tar
get/product/kugo/system/etc/libnfc-nci.conf'
build/make/core/base_rules.mk:525: warning: ignoring old commands for target 
`out/target/product/kugo/system/etc/libnfc-nci.conf'
[  0% 223/60947] build out/target/product/kugo/obj/KERNEL_OBJ/.additional_con
ninja: Missing `restat`? An output file is older than the most recent input:
 output: out/target/product/kugo/obj/KERNEL_OBJ/.additional_config
  input: out/target/product/kugo/obj/KERNEL_OBJ
[  0% 227/60947] build out/target/product/kugo/obj/ETC/sepolicy.recovery_inte
FAILED: out/target/product/kugo/obj/ETC/sepolicy.recovery_intermediates/sepol
icy
/bin/bash -c "(ASAN_OPTIONS=detect_leaks=0 out/host/linux-x86/bin/checkpolicy
 -M -c 		30 -o out/target/product/kugo/obj/ETC/sepolicy.recovery_inter
mediates/sepolicy.tmp out/target/product/kugo/obj/ETC/sepolicy.recovery_inter
mediates/sepolicy.recovery.conf ) && (out/host/linux-x86/bin/sepolicy-analyze
 out/target/product/kugo/obj/ETC/sepolicy.recovery_intermediates/sepolicy.tmp
 permissive > out/target/product/kugo/obj/ETC/sepolicy.recovery_intermediates
/sepolicy.permissivedomains ) && (if [ \"userdebug\" = \"user\" -a -s out/tar
get/product/kugo/obj/ETC/sepolicy.recovery_intermediates/sepolicy.permissived
omains ]; then 		echo \"==========\" 1>&2; 		echo \"ERROR:
 permissive domains not allowed in user builds\" 1>&2; 		echo \"List o
f invalid domains:\" 1>&2; 		cat out/target/product/kugo/obj/ETC/s
epolicy.recovery_intermediates/sepolicy.permissivedomains 1>&2; 		e
xit 1; 		fi ) && (mv out/target/product/kugo/obj/ETC/sepolicy.recovery
_intermediates/sepolicy.tmp out/target/product/kugo/obj/ETC/sepolicy.recovery
_intermediates/sepolicy )"
device/sony/loire-common/sepolicy/vendor/mlog_qmi_service.te:9:ERROR 'syntax 
error' at token 'msm_sock_ipc_ioctls' on line 82548:
allowxperm mlog_qmi_service self:socket ioctl msm_sock_ipc_ioctls;
allow mlog_qmi_service self:socket { create { ioctl read getattr write setatt
r lock append bind connect getopt setopt shutdown map } };
checkpolicy:  error(s) encountered while parsing configuration
[  0% 232/60947] build out/target/product/kugo/obj/FAKE/sepolicy_neverallows_
FAILED: out/target/product/kugo/obj/FAKE/sepolicy_neverallows_intermediates/s
epolicy_neverallows
/bin/bash -c "(ASAN_OPTIONS=detect_leaks=0 out/host/linux-x86/bin/checkpolicy
 -M -c 		30 -o out/target/product/kugo/obj/FAKE/sepolicy_neverallows_i
ntermediates/sepolicy_neverallows.tmp out/target/product/kugo/obj/FAKE/sepoli
cy_neverallows_intermediates/policy.conf ) && (out/host/linux-x86/bin/sepolic
y-analyze out/target/product/kugo/obj/FAKE/sepolicy_neverallows_intermediates
/sepolicy_neverallows.tmp neverallow -w -f out/target/product/kugo/obj/FAKE/s
epolicy_neverallows_intermediates/policy_2.conf || 	  ( echo \"\" 1>&2;  
   echo \"sepolicy-analyze failed. This is most likely due to the use\" 1>&2;
 	    echo \"of an expanded attribute in a neverallow assertion. Please
 fix\" 1>&2; 	    echo \"the policy.\" 1>&2; 	    exit 1 ) ) && (touch out/
target/product/kugo/obj/FAKE/sepolicy_neverallows_intermediates/sepolicy_neve
rallows.tmp ) && (mv out/target/product/kugo/obj/FAKE/sepolicy_neverallows_in
termediates/sepolicy_neverallows.tmp out/target/product/kugo/obj/FAKE/sepolic
y_neverallows_intermediates/sepolicy_neverallows )"
device/sony/loire-common/sepolicy/vendor/mlog_qmi_service.te:9:ERROR 'syntax 
error' at token 'msm_sock_ipc_ioctls' on line 78146:
allowxperm mlog_qmi_service self:socket ioctl msm_sock_ipc_ioctls;
allow mlog_qmi_service self:socket { create { ioctl read getattr write setatt
r lock append bind connect getopt setopt shutdown map } };
checkpolicy:  error(s) encountered while parsing configuration
[  0% 234/60947] Building Kernel Config
make: Entering directory '/home/r/miku/kernel/sony/msm8956'
  GEN     /home/r/miku/out/target/product/kugo/obj/KERNEL_OBJ/Makefile
#
# configuration written to .config
#
make: Leaving directory '/home/r/miku/kernel/sony/msm8956'
make: Entering directory '/home/r/miku/kernel/sony/msm8956'
  GEN     /home/r/miku/out/target/product/kugo/obj/KERNEL_OBJ/Makefile
scripts/kconfig/conf --savedefconfig=defconfig Kconfig
make: Leaving directory '/home/r/miku/kernel/sony/msm8956'
22:49:52 ninja failed with: exit status 1

#### failed to build some targets (03:03 (mm:ss)) ####

r@ubuntu:~/miku$

**Comment by AmeChanRain** [comment]
Looks like sepolicy issues, review your device tree. : )
