### ISSUE TITLE
Build error, please help me!

### ISSUE THREAD

**Issue by sopy264** [Miku-UI/manifesto#9]
嘛，想编一个miku ui TDA给xaga（redmi n11tp）
然后炸力
使用的是archlinux,安装了AUR包lineageos-devel aosp-devel 以及f2fs-tools
github.com/sopy264/device_xiaomi_xaga
github.com/mt6787-dev/android_device_mediatek_sepolicy_vndr
gitlab.com/yadavmohit19/vendor_xiaomi_xaga (branch 13)
github.com/yadavmohit19/kernel_xiaomi_xaga

![image](https://i.postimg.cc/6q3bJRQX/image.png)

**Comment by AmeChanRain** [comment]
你的device里包含了不存在的packages哦，请仔细检查！(o-ωｑ))

**Comment by sopy264** [comment]
但是这串其实来自于源中，没在树里捏

**Comment by AmeChanRain** [comment]
你的device源码中，引用了这个makefile：
https://github.com/YadavMohit19/device_xiaomi_xaga/blob/13/device.mk#L11
而此makefile中提供的部分packages并不存在，这是AOSP自身的疏漏，相关：
https://github.com/LineageOS/android_external_e2fsprogs/commit/9b8f6573cb42e0c87e7f22427b71cc883fa33428
你可以通过Pick这个patch来解决

Miku UI不会主动去支持非官方的设备构建，所以还请自行解决。
